# Remote Commander Key Translation Maps

remoteMaps:
  remoteCommanderMap0:
    name : "example_all_keys"
    prefix: ""
    codes:
      A: "A"
      ANTENNA: "ANTENNA"
      APPS: "APPS"
      ARC: "ARC"
      ARROW_UP: "ARROW_UP"
      ARROW_DOWN: "ARROW_DOWN"
      ARROW_LEFT: "ARROW_LEFT"
      ARROW_RIGHT: "ARROW_RIGHT"
      AUDIO: "AUDIO"
      AUD_DESC: "AUD_DESC"
      AUX: "AUX"
      B: "B"
      BI: "BI"
      BACK: "BACK"
      BAND: "BAND"
      BLK: "BLK"
      BLUE: "BLUE"
      BLUETOOTH: "BLUETOOTH"
      C: "C"
      CANCEL: "CANCEL"
      CBL_SAT: "CBL_SAT"
      CCTT: "CCTT"
      CH_SCAN: "CH_SCAN"
      CHANNEL_UP: "CHANNEL_UP"
      CHANNEL_DOWN: "CHANNEL_DOWN"
      CI_PLUS: "CI+"
      CLONE: "CLONE"
      CROSS: "CROSS"
      CSM: "CSM"
      CTC: "CTC"
      CVBS: "CVBS"
      D: "D"
      D2D3: "D2D3"
      DCR: "DCR"
      DISC_MENU: "DISC_MENU"
      DISNEY: "DISNEY"
      DVD: "DVD"
      ECO: "ECO"
      ELLIPSIS: "ELLIPSIS"
      EJECT: "EJECT"
      ENHANCER: "ENHANCER"
      EXIT: "EXIT"
      FAC: "FAC"
      FFORWARD: "FFORWARD"
      GREEN: "GREEN"
      GUIDE: "GUIDE"
      HDMI: "HDMI"
      HEART: "HEART"
      HELP: "HELP"
      HOME: "HOME"
      INFO: "INFO"
      INPUT_DOWN: "INPUT_DOWN"
      INPUT_UP: "INPUT_UP"
      INTERNET: "INTERNET"
      INTERNET_RADIO: "INTERNET_RADIO"
      LAST: "LAST"
      LIGHT_SENSOR: "LIGHT_SENSOR"
      LOBATT: "LOBATT"
      LOG_LED: "LOG_LED"
      MENU: "MENU"
      MIC: "MIC"
      MIRACAST: "MIRACAST"
      MODE: "MODE"
      MORE: "MORE"
      MOVIE: "MOVIE"
      MUSIC: "MUSIC"
      MUTE: "MUTE"
      NETFLIX: "NETFLIX"
      NUM_0: "NUM_0"
      NUM_1: "NUM_1"
      NUM_2: "NUM_2"
      NUM_3: "NUM_3"
      NUM_4: "NUM_4"
      NUM_5: "NUM_5"
      NUM_6: "NUM_6"
      NUM_7: "NUM_7"
      NUM_8: "NUM_8"
      NUM_9: "NUM_9"
      OPTIONS: "OPTIONS"
      PAGE_DOWN: "PAGE_DOWN"
      PAGE_UP: "PAGE_UP"
      PARENT: "PARENT"
      PARTY: "PARTY"
      PASSTHROUGH: "PASSTHROUGH"
      PATTERN: "PATTERN"
      PAUSE: "PAUSE"
      PEACOCK: "PEACOCK"
      PHONO: "PHONO"
      PIC: "PIC"
      PICK_UP: "PICK_UP"
      PLAY: "PLAY"
      POPUP_MENU: "POPUP_MENU"
      POWER: "POWER"
      PRESET_LEFT: "PRESET_LEFT"
      PRESET_RIGHT: "PRESET_RIGHT"
      PREV_CH: "PREV_CH"
      PRIME_VIDEO: "PRIME_VIDEO"
      QUESTION: "QUESTION"
      RECORD: "RECORD"
      RED: "RED"
      REGIN: "REGIN"
      REPLAY: "REPLAY"
      RESERVE1: "RESERVE1"
      RESERVE2: "RESERVE2"
      REWIND: "REWIND"
      RGYB: "RGYB"
      RJ45: "RJ45"
      RS232: "RS232"
      RESET: "RESET"
      SEARCH: "SEARCH"
      SELECT: "SELECT"
      SETUP: "SETUP"
      SKY: "SKY"
      SOURCE: "SOURCE"
      STANDBY: "STANDBY"
      STATUS: "STATUS"
      STOP: "STOP"
      SUBTITLE: "SUBTITLE"
      SURROUND: "SURROUND"
      SUR_DECODE: "SUR_DECODE"
      TEST: "TEST"
      TEXT: "TEXT"
      TOOLS: "TOOLS"
      TUNING_LEFT: "TUNING_LEFT"
      TUNING_RIGHT: "TUNING_RIGHT"
      USB: "USB"
      VGA: "VGA"
      VIRGIN: "VIRGIN"
      VOL_DOWN: "VOL_DOWN"
      VOL_UP: "VOL_UP"
      WIFI_SSID: "WIFI_SSID"
      WP: "WP"
      XFINITY: "XFINITY"
      YELLOW: "YELLOW"
