# Remote Commander Key Translation Maps

remoteMaps:
    remoteCommanderMap0:
        name : "apple_tv"
        prefix: "NEC_b="
        codes:
            MENU: "Menu"
            PAUSE: "Pause"
            ARROW_UP: "NavUp"
            ARROW_LEFT: "NavLeft"
            ARROW_RIGHT: "NavRight"
            ARROW_DOWN: "NavDown"
            SELECT: "NavEnter"

    remoteCommanderMap1:
        name : "denon_rc1227_zone1"
        prefix: "PANA_b="
        codes:
            NUM_1: "1"
            NUM_2: "2"
            NUM_3: "3"
            NUM_4: "4"
            AUX: "Aux"
            BACK: "Back"
            BLURAY: "BluRay"
            BLUETOOTH: "Bluetooth"
            CBL_SAT: "CblSat"
            CHANNEL_DOWN: "ChPgDown"
            CHANNEL_UP: "ChPgUp"
            DVD: "Dvd"
            ECO: "Eco"
            BLUE: "Game"
            INFO: "Info"
            INTERNET_RADIO: "InternetRadio"
            MEDIA_PLAYER: "MediaPlayer"
            GREEN: "Movie"
            RED: "Music"
            MUTE: "Mute"
            SELECT: "NavCenter"
            ARROW_DOWN: "NavDown"
            ARROW_LEFT: "NavLeft"
            ARROW_RIGHT: "NavRight"
            ARROW_UP: "NavUp"
            POWER: "OnOff"
            OPTIONS: "Option"
            PAUSE: "Pause"
            PHONO: "Phono"
            YELLOW: "Pure"
            SETUP: "Setup"
            STANDBY: "Sleep"
            FFORWARD: "Tune+"
            REWIND: "Tune-"
            TUNER: "Tuner"
            AUDIO: "TvAudio"
            USB: "Usb"
            VOL_DOWN: "VolDown"
            VOL_UP: "VolUp"

    remoteCommanderMap2:
        name: "denon_rc1227_zone2"
        prefix: "PANA_c="
        codes:
            NUM_1: "1"
            NUM_2: "2"
            NUM_3: "3"
            NUM_4: "4"
            AUX: "Aux"
            BACK: "Back"
            BLURAY: "BluRay"
            BLUETOOTH: "Bluetooth"
            CBL_SAT: "CblSat"
            CHANNEL_DOWN: "ChPgDown"
            CHANNEL_UP: "ChPgUp"
            DVD: "Dvd"
            BLUE: "Game"
            INTERNET_RADIO: "InternetRadio"
            MEDIA_PLAYER: "MediaPlayer"
            MUTE: "Mute"
            SELECT: "NavCenter"
            ARROW_DOWN: "NavDown"
            ARROW_LEFT: "NavLeft"
            ARROW_RIGHT: "NavRight"
            ARROW_UP: "NavUp"
            POWER: "OnOff"
            PAUSE: "Pause"
            PHONO: "Phono"
            STANDBY: "Sleep"
            FFORWARD: "Tune+"
            REWIND: "Tune-"
            TUNER: "Tuner"
            AUDIO: "TvAudio"
            USB: "Usb"
            VOL_DOWN: "VolDown"
            VOL_UP: "VolUp"

    remoteCommanderMap3:
        name: "hisense_platco"
        prefix: "XMP_a="
        codes:
            NUM_0: "0"
            NUM_1: "1"
            NUM_2: "2"
            NUM_3: "3"
            NUM_4: "4"
            NUM_5: "5"
            NUM_6: "6"
            NUM_7: "7"
            NUM_8: "8"
            NUM_9: "9"
            BACK: "Back"
            CROSS: "Cross"
            DISNEY: "Disney"
            HOME: "Home"
            SOURCE: "Input"
            MENU: "Menu"
            MIC: "Mic"
            MUTE: "Mute"
            ARROW_DOWN: "NavDown"
            SELECT: "NavEnter"
            ARROW_LEFT: "NavLeft"
            ARROW_RIGHT: "NavRight"
            ARROW_UP: "NavUp"
            NETFLIX: "Netflix"
            POWER: "OnOff"
            OPTIONS: "Options"
            PEACOCK: "Peacock"
            PRIME_VIDEO: "PrimeVideo"
            VOL_DOWN: "VolDown"
            VOL_UP: "VolUp"

    remoteCommanderMap4:
        name: "xumo_pr1"
        prefix: "XMP_e="
        codes:
            NUM_0: "0"
            NUM_1: "1"
            NUM_2: "2"
            NUM_3: "3"
            NUM_4: "4"
            NUM_5: "5"
            NUM_6: "6"
            NUM_7: "7"
            NUM_8: "8"
            NUM_9: "9"
            BACK: "Back"
            CROSS: "Cross"
            HOME: "Home"
            SOURCE: "Input"
            MENU: "Menu"
            MIC: "Mic"
            MUTE: "Mute"
            ARROW_DOWN: "NavDown"
            SELECT: "NavEnter"
            ARROW_LEFT: "NavLeft"
            ARROW_RIGHT: "NavRight"
            ARROW_UP: "NavUp"
            NETFLIX: "Netflix"
            POWER: "OnOff"
            OPTIONS: "Options"
            PEACOCK: "Peacock"
            PRIME_VIDEO: "PrimeVideo"
            VOL_DOWN: "VolDown"
            VOL_UP: "VolUp"
            XUMO: "Xumo"

    remoteCommanderMap5:
        name: "panasonic_dp-ub820"
        prefix: "PANA_a="
        codes:
            NUM_0: "0"
            NUM_1: "1"
            NUM_2: "2"
            NUM_3: "3"
            NUM_4: "4"
            NUM_5: "5"
            NUM_6: "6"
            NUM_7: "7"
            NUM_8: "8"
            NUM_9: "9"
            AUDIO: "Audio"
            BLUE: "Blue"
            CANCEL: "Cancel"
            EXIT: "Exit"
            GREEN: "Green"
            HOME: "Home"
            INTERNET: "Internet"
            MIRACAST: "Miracast"
            SELECT: "NavCenter"
            ARROW_DOWN: "NavDown"
            ARROW_LEFT: "NavLeft"
            ARROW_RIGHT: "NavRight"
            ARROW_UP: "NavUp"
            NETFLIX: "Netflix"
            FFORWARD: "Next"
            STANDBY: "OnOff"
            EJECT: "OpenClose"
            OPTIONS: "Option"
            PAUSE: "Pause"
            PLAY: "Play"
            POPUP_MENU: "PopUpMenu"
            REWIND: "Previous"
            RED: "Red"
            BACK: "Return"
            SEARCH_BACK: "SearchBackward"
            SEARCH_FWD: "SearchForward"
            STATUS: "Status"
            STOP: "Stop"
            MENU: "TopMenu"
            SOURCE: "TvInputAv"
            POWER: "TvOnOff"
            VOL_DOWN: "TvVolDown"
            VOL_UP: "TvVolUp"
            YELLOW: "Yellow"

    remoteCommanderMap6:
        name: "rav575_zone1"
        prefix: "NEC_c="
        codes:
            NUM_1: "1"
            NUM_2: "2"
            NUM_3: "3"
            NUM_4: "4"
            BAND: "Band"
            BLUE: "Blue"
            BLUETOOTH: "Bluetooth"
            DISPLAY: "Display"
            ENHANCER: "Enhancer"
            GREEN: "Green"
            HOME: "Home"
            CHANNEL_DOWN: "InputDown"
            CHANNEL_UP: "InputUp"
            REWIND: "MemLeft"
            PLAY: "MemPlay"
            FFORWARD: "MemRight"
            MODE: "Mode"
            MUTE: "Mute"
            SELECT: "NavCenter"
            ARROW_DOWN: "NavDown"
            ARROW_LEFT: "NavLeft"
            ARROW_RIGHT: "NavRight"
            ARROW_UP: "NavUp"
            INTERNET: "Net"
            POWER: "OnOff"
            OPTIONS: "Option"
            PARTY: "Party"
            POPUP_MENU: "PopUpMenu"
            PRESET_LEFT: "PresetLeft"
            PRESET_RIGHT: "PresetRight"
            PROG_LEFT: "ProgLeft"
            PROG_RIGHT: "ProgRight"
            PASSTHROUGH: "PureDirect"
            RED: "Red"
            BACK: "Return"
            SETUP: "Setup"
            STANDBY: "Sleep"
            STRAIGHT: "Straight"
            SUR_DECODE: "SurDecode"
            MENU: "TopMenu"
            SEARCH_BACK: "TuningLeft"
            SEARCH_FWD: "TuningRight"
            USB: "Usb"
            VOL_DOWN: "VolDown"
            VOL_UP: "VolUp"
            YELLOW: "Yellow"

    remoteCommanderMap7:
        name: "rav575_zone2"
        prefix: "NEC_d="
        codes:
            NUM_1: "1"
            NUM_2: "2"
            NUM_3: "3"
            NUM_4: "4"
            BAND: "Band"
            BLUE: "Blue"
            BLUETOOTH: "Bluetooth"
            DISPLAY: "Display"
            ENHANCER: "Enhancer"
            GREEN: "Green"
            HOME: "Home"
            CHANNEL_DOWN: "InputDown"
            CHANNEL_UP: "InputUp"
            REWIND: "MemLeft"
            PLAY: "MemPlay"
            FFORWARD: "MemRight"
            MODE: "Mode"
            MUTE: "Mute"
            SELECT: "NavCenter"
            ARROW_DOWN: "NavDown"
            ARROW_LEFT: "NavLeft"
            ARROW_RIGHT: "NavRight"
            ARROW_UP: "NavUp"
            INTERNET: "Net"
            POWER: "OnOff"
            OPTIONS: "Option"
            PARTY: "Party"
            POPUP_MENU: "PopUpMenu"
            PRESET_LEFT: "PresetLeft"
            PRESET_RIGHT: "PresetRight"
            PROG_LEFT: "ProgLeft"
            PROG_RIGHT: "ProgRight"
            RED: "Red"
            BACK: "Return"
            SETUP: "Setup"
            STANDBY: "Sleep"
            MENU: "TopMenu"
            SEARCH_BACK: "TuningLeft"
            SEARCH_FWD: "TuningRight"
            USB: "Usb"
            VOL_DOWN: "VolDown"
            VOL_UP: "VolUp"
            YELLOW: "Yellow"

    remoteCommanderMap8:
        name: "samsung_ubd-k8500"
        prefix: "SAM_a="
        codes:
            RED: "A"
            GREEN: "B"
            YELLOW: "C"
            BLUE: "D"
            DISC_MENU: "DiscMenu"
            EJECT: "Eject"
            BACK: "Back"
            HOME: "Home"
            INFO: "Info"
            SELECT: "NavEnter"
            ARROW_DOWN: "NavDown"
            ARROW_LEFT: "NavLeft"
            ARROW_RIGHT: "NavRight"
            ARROW_UP: "NavUp"
            FFORWARD: "Next"
            STANDBY: "OnOff"
            PAUSE: "Pause"
            REWIND: "Previous"
            STOP: "Stop"
            POWER: "TvPower"
            SOURCE: "TvSource"
            VOL_DOWN: "TvVolDown"
            VOL_UP: "TvVolUp"
            MENU: "TitleMenu"
            TOOLS: "Tools"

    remoteCommanderMap9:
        name: "sony_ubp-x800m2"
        prefix: "SIRC_a="
        codes:
            AUDIO: "Audio"
            STANDBY: "OnOff"
            BLUE: "Blue"
            DISPLAY: "Display"
            EJECT: "Eject"
            SEARCH_FWD: "Forward"
            GREEN: "Green"
            HEART: "Heart"
            HOME: "Home"
            MUTE: "Mute"
            SELECT: "NavEnter"
            ARROW_DOWN: "NavDown"
            ARROW_LEFT: "NavLeft"
            ARROW_RIGHT: "NavRight"
            ARROW_UP: "NavUp"
            NETFLIX: "Netflix"
            FFORWARD: "Next"
            OPTIONS: "Options"
            PAUSE: "Pause"
            PLAY: "Play"
            POPUP_MENU: "PopUpMenu"
            REWIND: "Previous"
            RED: "Red"
            BACK: "Return"
            SEARCH_BACK: "Rewind"
            STOP: "Stop"
            SUBTITLE: "Subtitle"
            SOURCE: "TvInput"
            POWER: "TvOnOff"
            MENU: "TopMenu"
            VOL_DOWN: "VolDown"
            VOL_UP: "VolUp"
            YELLOW: "Yellow"

    remoteCommanderMap10:
        name: "tpv"
        prefix: "TPV="
        codes:
            NUM_0: "0"
            NUM_1: "1"
            NUM_2: "2"
            THREE_D: "2D3D"
            NUM_3: "3"
            NUM_4: "4"
            NUM_5: "5"
            NUM_6: "6"
            NUM_7: "7"
            NUM_8: "8"
            NUM_9: "9"
            ANTENNA: "AntennaCable"
            ARC: "Arc"
            AUDIO: "Audio"
            BI: "BI"
            BLK: "Blk"
            CCTT: "Cctt"
            CHANNEL_UP: "Ch+"
            CHANNEL_DOWN: "Ch-"
            CH_SCAN: "ChScan"
            CI_PLUS: "Ci+"
            CLONE: "Clone"
            CSM: "Csm"
            CTC: "Ctc"
            CVBS: "Cvbs"
            DCR: "Dcr"
            FAC: "Fac"
            HDMI: "Hdmi"
            LIGHT_SENSOR: "LightSensor"
            LOG_LED: "LogLed"
            MENU: "Menu"
            MUTE: "Mute"
            ARROW_DOWN: "NavDown"
            SELECT: "NavEnter"
            ARROW_LEFT: "NavLeft"
            ARROW_RIGHT: "NavRight"
            ARROW_UP: "NavUp"
            PATTERN: "Pattern"
            PIC: "Pic"
            PREV_CH: "PreCh"
            REGIN: "Regin"
            RESERVE1: "Reserve1"
            RESERVE2: "Reserve2"
            RJ45: "Rj45"
            RS232: "Rs232"
            RESET: "Rst"
            TEST: "Test"
            USB: "Usb"
            VGA: "Vga"
            VIRGIN: "Virgin"
            VOL_DOWN: "VolBuzz"
            VOL_UP: "VolMax"
            WIFI_SSID: "WifiSsid"
            WP: "Wp"
            YPBPR_SCART: "YpbprScart"

    remoteCommanderMap11:
        name: "xr100"
        prefix: "XMP_d="
        codes:
            NUM_0: "0"
            NUM_1: "1"
            NUM_2: "2"
            NUM_3: "3"
            NUM_4: "4"
            NUM_5: "5"
            NUM_6: "6"
            NUM_7: "7"
            NUM_8: "8"
            NUM_9: "9"
            BACK: "Back"
            CROSS: "Cross"
            HOME: "Home"
            SOURCE: "Input"
            MENU: "Menu"
            MIC: "Mic"
            MUTE: "Mute"
            ARROW_DOWN: "NavDown"
            SELECT: "NavEnter"
            ARROW_LEFT: "NavLeft"
            ARROW_RIGHT: "NavRight"
            ARROW_UP: "NavUp"
            POWER: "OnOff"
            PAUSE: "Pause"
            PICK_UP: "PickUp" # Not a key on the remote but a signal it can send.
            VOL_DOWN: "VolDown"
            VOL_UP: "VolUp"

    remoteCommanderMap12:
        name: "llama_a"
        prefix: "RC6_a="
        codes:
            NUM_0: "0"
            NUM_1: "1"
            NUM_2: "2"
            NUM_3: "3"
            NUM_4: "4"
            NUM_5: "5"
            NUM_6: "6"
            NUM_7: "7"
            NUM_8: "8"
            NUM_9: "9"
            BACK: "Back"
            CROSS: "Cross"
            HOME: "Home"
            MENU: "Menu"
            MIC: "Mic"
            MUTE: "Mute"
            ARROW_DOWN: "NavDown"
            SELECT: "NavEnter"
            ARROW_LEFT: "NavLeft"
            ARROW_RIGHT: "NavRight"
            ARROW_UP: "NavUp"
            POWER: "OnOff"
            PAUSE: "Pause"
            PICK_UP: "PickUp" # Not a key on the remote but a signal it can send.
            RGYB: "Rgyb"
            VOL_DOWN: "VolDown"
            VOL_UP: "VolUp"

    remoteCommanderMap13:
        name: "llama_b"
        prefix: "RC6_b="
        codes:
            NUM_0: "0"
            NUM_1: "1"
            NUM_2: "2"
            NUM_3: "3"
            NUM_4: "4"
            NUM_5: "5"
            NUM_6: "6"
            NUM_7: "7"
            NUM_8: "8"
            NUM_9: "9"
            BACK: "Back"
            CROSS: "Cross"
            HOME: "Home"
            MENU: "Menu"
            MIC: "Mic"
            MUTE: "Mute"
            ARROW_DOWN: "NavDown"
            SELECT: "NavEnter"
            ARROW_LEFT: "NavLeft"
            ARROW_RIGHT: "NavRight"
            ARROW_UP: "NavUp"
            POWER: "OnOff"
            PAUSE: "Pause"
            RGYB: "Rgyb"
            VOL_DOWN: "VolDown"
            VOL_UP: "VolUp"

    remoteCommanderMap14:
        name: "llama_c"
        prefix: "RC6_c="
        codes:
            NUM_0: "0"
            NUM_1: "1"
            NUM_2: "2"
            NUM_3: "3"
            NUM_4: "4"
            NUM_5: "5"
            NUM_6: "6"
            NUM_7: "7"
            NUM_8: "8"
            NUM_9: "9"
            BACK: "Back"
            BLUE: "BlueDot"
            CHANNEL_UP: "Ch+"
            CHANNEL_DOWN: "Ch-"
            FFORWARD: "Forward"
            GREEN: "GreenDot"
            HOME: "Home"
            SOURCE: "Input"
            SEARCH: "Mag"
            MENU: "Menu"
            MIC: "Mic"
            MUTE: "Mute"
            ARROW_DOWN: "NavDown"
            SELECT: "NavEnter"
            ARROW_LEFT: "NavLeft"
            ARROW_RIGHT: "NavRight"
            ARROW_UP: "NavUp"
            POWER: "OnOff"
            PAUSE: "Pause"
            RECORD: "R"
            RED: "RedDot"
            REWIND: "Rewind"
            VOL_DOWN: "VolDown"
            VOL_UP: "VolUp"
            YELLOW: "YellowDot"

    remoteCommanderMap15:
        name: "llama_d"
        prefix: "RC6_d="
        codes:
            NUM_0: "0"
            NUM_1: "1"
            NUM_2: "2"
            NUM_3: "3"
            NUM_4: "4"
            NUM_5: "5"
            NUM_6: "6"
            NUM_7: "7"
            NUM_8: "8"
            NUM_9: "9"
            BACK: "Back"
            BLUE: "BlueDot"
            CHANNEL_UP: "Ch+"
            CHANNEL_DOWN: "Ch-"
            FFORWARD: "Forward"
            GREEN: "GreenDot"
            HOME: "Home"
            INFO: "I"
            SOURCE: "Input"
            SEARCH: "Mag"
            MENU: "Menu"
            MUTE: "Mute"
            ARROW_DOWN: "NavDown"
            SELECT: "NavEnter"
            ARROW_LEFT: "NavLeft"
            ARROW_RIGHT: "NavRight"
            ARROW_UP: "NavUp"
            POWER: "OnOff"
            PAUSE: "Pause"
            QUESTION: "Question"
            RECORD: "R"
            RED: "RedDot"
            REWIND: "Rewind"
            SKY: "Sky"
            VOL_DOWN: "VolDown"
            VOL_UP: "VolUp"
            YELLOW: "YellowDot"

    remoteCommanderMap16:
        name: "xfinity1"
        prefix: "XMP_b="
        codes:
            NUM_0: "0"
            NUM_1: "1"
            NUM_2: "2"
            NUM_3: "3"
            NUM_4: "4"
            NUM_5: "5"
            NUM_6: "6"
            NUM_7: "7"
            NUM_8: "8"
            NUM_9: "9"
            A: "A"
            B: "B"
            BACK: "Back"
            C: "C"
            CHANNEL_UP: "Ch+"
            CHANNEL_DOWN: "Ch-"
            D: "D"
            EXIT: "Exit"
            FFORWARD: "Forward"
            GUIDE: "Guide"
            INFO: "I"
            MIC: "Mic"
            MUTE: "Mute"
            ARROW_DOWN: "NavDown"
            SELECT: "NavEnter"
            ARROW_LEFT: "NavLeft"
            ARROW_RIGHT: "NavRight"
            ARROW_UP: "NavUp"
            POWER: "OnOff"
            PAUSE: "Pause"
            PAGE_DOWN: "PgDown"
            PAGE_UP: "PgUp"
            RECORD: "Record"
            REWIND: "Rewind"
            SOURCE: "TvInput"
            VOL_DOWN: "VolDown"
            VOL_UP: "VolUp"
            XFINITY: "Xfinity"

    remoteCommanderMap17:
        name: "xfinity2"
        prefix: "XMP_c="
        codes:
            NUM_0: "0"
            NUM_1: "1"
            NUM_2: "2"
            NUM_3: "3"
            NUM_4: "4"
            NUM_5: "5"
            NUM_6: "6"
            NUM_7: "7"
            NUM_8: "8"
            NUM_9: "9"
            A: "A"
            B: "B"
            C: "C"
            CHANNEL_UP: "Ch+"
            CHANNEL_DOWN: "Ch-"
            D: "D"
            EXIT: "Exit"
            FFORWARD: "Forward"
            GUIDE: "Guide"
            INFO: "Info"
            PREV_CH: "Last"
            MIC: "Mic"
            MUTE: "Mute"
            ARROW_DOWN: "NavDown"
            SELECT: "NavEnter"
            ARROW_LEFT: "NavLeft"
            ARROW_RIGHT: "NavRight"
            ARROW_UP: "NavUp"
            POWER: "OnOff"
            PAUSE: "Pause"
            PAGE_DOWN: "PgDown"
            PAGE_UP: "PgUp"
            RECORD: "Record"
            REPLAY: "Replay"
            REWIND: "Rewind"
            SETUP: "Setup"
            SOURCE: "TvInput"
            STANDBY: "TvPower"
            VOL_DOWN: "VolDown"
            VOL_UP: "VolUp"
            XFINITY: "Xfinity"